#!/usr/bin/env node
/*
 * Builds server/data/places.json, the offline city index behind place search.
 *
 * Source: GeoNames cities (CC BY 4.0) via the `all-the-cities` package.
 * Run with: npm run build:places  (needs dev dependencies installed)
 *
 * Output shape:
 *   { version, attribution, countries: { US: "USA", ... },
 *     places: [[name, countryCode, region, lat, lng, population], ...] }
 */
const fs = require('fs');
const path = require('path');
const cities = require('all-the-cities');

const MIN_POPULATION = 5000;
const ALWAYS_INCLUDE = new Set(['PPLC', 'PPLA', 'PPLA2']);

// Short, familiar names. Everything else comes from Intl.DisplayNames.
const COUNTRY_OVERRIDES = {
  US: 'USA', GB: 'UK', AE: 'UAE', KR: 'South Korea', KP: 'North Korea',
  CZ: 'Czech Republic', HK: 'Hong Kong', MO: 'Macau', CD: 'DR Congo',
  CG: 'Republic of the Congo', MM: 'Myanmar', PS: 'Palestine', VA: 'Vatican City',
  TR: 'Turkey', RU: 'Russia', TW: 'Taiwan', CV: 'Cape Verde', FM: 'Micronesia',
  VN: 'Vietnam', LA: 'Laos', SY: 'Syria', IR: 'Iran', BO: 'Bolivia', VE: 'Venezuela',
  TZ: 'Tanzania', MD: 'Moldova', BN: 'Brunei', PR: 'Puerto Rico',
};

const CA_REGIONS = { '01': 'AB', '02': 'BC', '03': 'MB', '04': 'NB', '05': 'NL', '07': 'NS', '08': 'ON', '09': 'PE', '10': 'QC', '11': 'SK', '12': 'YT', '13': 'NT', '14': 'NU' };
const AU_REGIONS = { '01': 'ACT', '02': 'NSW', '03': 'NT', '04': 'QLD', '05': 'SA', '06': 'TAS', '07': 'VIC', '08': 'WA' };

// Well-known places people say they are "from" or "know well" that are not
// cities in GeoNames, or are below the population cutoff.
const EXTRA_PLACES = [
  ['Bali', 'ID', '', -8.4095, 115.1889, 4300000],
  ['Santorini', 'GR', '', 36.3932, 25.4615, 15000],
  ['Mykonos', 'GR', '', 37.4467, 25.3289, 10000],
  ['Positano', 'IT', '', 40.6281, 14.4850, 4000],
  ['Amalfi', 'IT', '', 40.6340, 14.6027, 5000],
  ['Maui', 'US', 'HI', 20.7984, -156.3319, 165000],
  ['The Hamptons', 'US', 'NY', 40.9634, -72.1848, 60000],
  ["Martha's Vineyard", 'US', 'MA', 41.3805, -70.6456, 20000],
  ['Montauk', 'US', 'NY', 41.0359, -71.9545, 4000],
  ['Sayulita', 'MX', '', 20.8687, -105.4407, 5000],
  ['Canggu', 'ID', '', -8.6478, 115.1385, 20000],
  ['Lake Como', 'IT', '', 46.0160, 9.2572, 50000],
  ['Mallorca', 'ES', '', 39.6953, 3.0176, 900000],
  ['Tuscany', 'IT', '', 43.7711, 11.2486, 3700000],
  ['Silicon Valley', 'US', 'CA', 37.3875, -122.0575, 3000000],
];

function intlCountryName(code) {
  try {
    const display = new Intl.DisplayNames(['en'], { type: 'region' });
    return display.of(code).replace(/ & /g, ' and ');
  } catch {
    return code;
  }
}

function countryName(code) {
  return COUNTRY_OVERRIDES[code] || intlCountryName(code);
}

function region(city) {
  if (city.country === 'US') return /^[A-Z]{2}$/.test(city.adminCode) ? city.adminCode : '';
  if (city.country === 'CA') return CA_REGIONS[city.adminCode] || '';
  if (city.country === 'AU') return AU_REGIONS[city.adminCode] || '';
  return '';
}

const round = (n) => Math.round(n * 10000) / 10000;

const kept = cities.filter((c) => c.population >= MIN_POPULATION || ALWAYS_INCLUDE.has(c.featureCode));
const places = kept.map((c) => [
  c.name,
  c.country,
  region(c),
  round(c.loc.coordinates[1]),
  round(c.loc.coordinates[0]),
  c.population || 0,
]);

for (const extra of EXTRA_PLACES) places.push(extra);
places.sort((a, b) => b[5] - a[5]);

const countries = {};
for (const place of places) {
  if (!countries[place[1]]) countries[place[1]] = countryName(place[1]);
}

const output = {
  version: 1,
  attribution: 'City data from GeoNames (CC BY 4.0), https://www.geonames.org',
  countries,
  places,
};

const target = path.join(__dirname, '..', 'server', 'data', 'places.json');
fs.writeFileSync(target, JSON.stringify(output));
console.log(`Wrote ${places.length} places in ${Object.keys(countries).length} countries to ${path.relative(process.cwd(), target)}`);

// Country name -> ISO code for flags in the browser. Includes the long and
// legacy spellings already stored on older atlas entries.
const byName = {};
for (const [code, name] of Object.entries(countries)) byName[name] = code;
for (const [code] of Object.entries(countries)) {
  const long = intlCountryName(code);
  if (!byName[long]) byName[long] = code;
}
Object.assign(byName, {
  'United States': 'US', 'United States of America': 'US', 'United Kingdom': 'GB', England: 'GB',
  Scotland: 'GB', Wales: 'GB', 'United Arab Emirates': 'AE', Czechia: 'CZ', 'Türkiye': 'TR',
  Korea: 'KR', Holland: 'NL',
});
const clientTarget = path.join(__dirname, '..', 'public', 'js', 'fa-countries.js');
fs.writeFileSync(clientTarget, `// Generated by scripts/build-places.js. Country name -> ISO 3166 code.\nwindow.FA_COUNTRIES=${JSON.stringify(byName)};\n`);
console.log(`Wrote ${Object.keys(byName).length} country names to ${path.relative(process.cwd(), clientTarget)}`);
